### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by chouaxong** [zhangrenyang/chatgpt#7] opened 2023-07-05 09:14 UTC
Request failed. The server could not understand or accept the sent request content. Please check your request content, including URL, request method, request headers, and request body. If the issue persists, please contact your service provider.

**Comment by zhangrenyang** [comment] 2023-07-05 11:33
Please close VS Code completely and then reopen the plugin.
Press Ctrl+Shift+P, type "ChatGPT: RefreshToken" to use it. If it doesn't work the first time, please refresh multiple times.
If the problem is resolved, please close this issue.

**Closed as completed** 2023-07-05 14:27 UTC

**Comment by chouaxong** [comment] 2023-07-07 03:45
problem is resolved, thanks
